[package]
name = "valor"
version = "0.1.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[dependencies]
#anyhow = "1.0.33"
async-std = { version = "1.6.5", default-features = false, features = ["std"] }
http-types = { version = "2.6.0", default-features = false }

[workspace]
members = [
	"valor-native",
	"valor-web",
]

[profile.release.package.valor-web]
opt-level = "s"
