[package]
name = "valib"
version = "0.1.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.68"
#console_error_panic_hook = { version = "0.1.6", optional = true }
# wee_alloc = { version = "0.4.5", optional = true }

#[profile.release]
#opt-level = "s"
