[package]
name = "valor-rs"
description = "Plugin runtime as HTTP API running in server and browser"
license = "GPL-3.0-or-later"
version = "0.2.0-alpha"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/valor"

[dependencies]
async-trait = "0.1.41"
fast-async-mutex = "0.6.3"
http-types = { version = "2.6.0", default-features = false }
path-tree = "0.1.12"
serde = { version = "1.0.117", default-features = false, features = ["alloc", "derive"] }
serde_json = "1.0.59"

[features]
web = []

[workspace]
default-members = ["valor-native"]
members = [
	"valor-native",
	"valor-web",
]

[profile.release.package.valor-web]
opt-level = "s"

[profile.release]
lto = true
