[package]
name = "valor"
version = "0.1.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[dependencies]
fast-async-mutex = "0.6.3"
http-types = { version = "2.6.0", default-features = false }
path-tree = "0.1.12"

[workspace]
members = [
	"valor-native",
	"valor-web",
]

[profile.release.package.valor-web]
opt-level = "s"
