[package]
name = "valor_lib"
description = "Plugin runtime as HTTP API running in server and browser"
license = "GPL-3.0-or-later"
version = "0.4.0-alpha.1"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/valor"

[dependencies]
async-trait = "0.1.42"
http-types = "2.8.0"
path-tree = "0.1.12"
serde = { version = "1.0.117", default-features = false, features = ["alloc", "derive"] }
serde_json = "1.0.59"
valor_plugin = { version = "0.4.0-alpha.0", path = "./valor_plugin", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.69", optional = true }
js-sys = { version = "0.3.46", optional = true }
wasm-bindgen-futures = { version = "0.4.19", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[target.'cfg(target_arch="wasm32")'.dependencies.web-sys]
version = "0.3.46"
optional = true
features = ["RequestInit", "Request", "ResponseInit", "Response", "Headers"]

[features]
util = ["valor_plugin"]
native = []
web = [
	"util",
	"wasm-bindgen", 
	"wasm-bindgen-futures", 
	"js-sys",
	"web-sys",
	"wee_alloc",
]

[workspace]
default-members = ["valor_native"]
members = [
	"valor_native",
	"valor_web",
	"valor_plugin",

	"examples/hello_plugin",
	"examples/with_state",
]

[profile.release.package.valor_web]
opt-level = "s"

[profile.release]
lto = true
