[package]
name = "valor-rs"
description = "Plugin runtime as HTTP API running in server and browser"
license = "GPL-3.0-or-later"
version = "0.2.0-alpha"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/valor"

[dependencies]
http-types = "2.8.0"
path-tree = "0.1.12"
serde = { version = "1.0.117", default-features = false, features = ["alloc", "derive"] }
serde_json = "1.0.59"
vlugin = { path = "./vlugin" }

[features]
native = []
web = []

[workspace]
default-members = ["valor-native"]
members = [
	"valor-native",
	"valor-web",
	"vlugin",

	"examples/hello-plugin"
]

[profile.release.package.valor-web]
opt-level = "s"

#[profile.release]
#lto = true
