[package]
name = "valor-web"
version = "0.1.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
valor = { path = ".." }
wasm-bindgen = "0.2.68"
wee_alloc = { version = "0.4.5", optional = true }

[profile.release]
opt-level = "s"
