[package]
name = "with_state"
version = "0.4.0-alpha.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[dependencies]
valor = { path = "../..", package = "valor_lib", features = ["util"] }

[lib]
crate-type = ["cdylib", "lib"]
