[package]
name = "hello-plugin"
version = "0.3.4"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[dependencies]
valor = { path = "../..", package = "valor-lib" }

[lib]
crate-type = ["dylib"]
