[package]
name = "valor-native"
version = "0.1.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[dependencies]
valor = { path = ".." }
tide = { version = "0.14.0", default-features = false, features = ["h1-server"] }
async-std = { version = "1.6.5", features = ["attributes"] }
