[package]
name = "valor-vlugin"
version = "0.3.2"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = "1.0.48"
